CREATE TABLE LIBRARY_MEMBER (
  U_ID            VARCHAR2(36) PRIMARY KEY NOT NULL,
  NATIONAL_NUMBER VARCHAR2(32) UNIQUE      NOT NULL,
  BIRTH_DATE      DATE                     NOT NULL,
  LAST_NAME       VARCHAR2(35)             NOT NULL,
  FIRST_NAME      VARCHAR2(35)             NOT NULL,
  ADDRESS          VARCHAR2(200),
  POSTAL_CODE     NUMBER(10),
  CITY            VARCHAR2(16),
  EMAIL           VARCHAR2(64),
  PHONE_NUMBER    VARCHAR2(14)
);