INSERT INTO CATEGORY VALUES(CATEGORY_SEQUENCE.nextVal, 'Science');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQUENCE.nextVal, 'Science-Fiction');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQUENCE.nextVal, 'Programming');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQUENCE.nextVal, 'Travel');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQUENCE.nextVal, 'Art');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQUENCE.nextVal, 'Series');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQUENCE.nextVal, 'History');
INSERT INTO CATEGORY VALUES(CATEGORY_SEQUENCE.nextVal, 'Agile');


INSERT INTO BOOK_CATEGORY VALUES(1, 1);
INSERT INTO BOOK_CATEGORY VALUES(1, 8);
INSERT INTO BOOK_CATEGORY VALUES(2, 1);
INSERT INTO BOOK_CATEGORY VALUES(2, 3);
INSERT INTO BOOK_CATEGORY VALUES(3, 3);
INSERT INTO BOOK_CATEGORY VALUES(4, 3);
INSERT INTO BOOK_CATEGORY VALUES(5, 8);
INSERT INTO BOOK_CATEGORY VALUES(5, 3);
INSERT INTO BOOK_CATEGORY VALUES(6, 3);
INSERT INTO BOOK_CATEGORY VALUES(7, 3);