CREATE TABLE BORROWED_HISTORY (
  HISTORY_ID NUMBER(5) PRIMARY KEY,
  BOOK_ID NUMBER(5),
  MEMBER_ID VARCHAR2(36) REFERENCES LIBRARY_MEMBER(U_ID),
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  CONSTRAINT fk_book FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE
);

CREATE SEQUENCE BORROWED_HISTORY_SEQUENCE
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE;


