CREATE TABLE AUTHOR (
  AUTHOR_ID NUMBER(5) PRIMARY KEY,
  FIRST_NAME VARCHAR2(255),
  LAST_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE AUTHOR_SEQUENCE
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE;