CREATE TABLE BOOK_AUTHOR (
  BOOK_ID NUMBER(5) REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,
  AUTHOR_ID NUMBER(5) REFERENCES AUTHOR(AUTHOR_ID) ON DELETE CASCADE,
  CONSTRAINT PK_BOOK_AUTHOR PRIMARY KEY (BOOK_ID, AUTHOR_ID)
);