CREATE TABLE BOOK_USER (
  USER_ID NUMBER(5) PRIMARY KEY,
  USERNAME VARCHAR2(55) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(64) NOT NULL,
  ENABLED NUMBER DEFAULT 1 NOT NULL
);

CREATE SEQUENCE BOOK_USER_SEQUENCE
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE;