INSERT INTO BOOK_USER VALUES(BOOK_USER_SEQUENCE.nextVal, 'admin', 'admin', 1);
INSERT INTO BOOK_USER VALUES(BOOK_USER_SEQUENCE.nextVal, 'iulia', 'iulia', 1);
INSERT INTO BOOK_USER VALUES(BOOK_USER_SEQUENCE.nextVal, 'vali', 'vali', 1);
INSERT INTO BOOK_USER VALUES(BOOK_USER_SEQUENCE.nextVal, 'geo', 'geo', 1);
