INSERT INTO BOOK_USER VALUES(BOOK_USER_SEQUENCE.nextVal, 'admin', '$2a$10$yDGIW4ni4OWPIT3ITEMPseTHRpzSNWHA.0RtyPc61qohA5OSB9OqO', 1);
INSERT INTO BOOK_USER VALUES(BOOK_USER_SEQUENCE.nextVal, 'iulia', '$2a$10$SdfDbdb5.dD.SqSffTD6HOgJiz3iOgWSLTmS9frp.PvMIwcZmKHAm', 1);
INSERT INTO BOOK_USER VALUES(BOOK_USER_SEQUENCE.nextVal, 'vali', '$2a$10$yphNKAQKt0c/eTHb8yRNgucXe6tN/NHPDtoQoUHijCsEZPg87y0kK', 1);
INSERT INTO BOOK_USER VALUES(BOOK_USER_SEQUENCE.nextVal, 'geo', '$2a$10$BSrUQvpWqJFNfFAk98y8uersLmA3WLS8yCterwMbR.UddQvISAu1e', 1);
