CREATE TABLE USER_ROLES (
  user_role_id NUMBER(11) NOT NULL PRIMARY KEY ,
  username VARCHAR2(45) NOT NULL UNIQUE ,
  role VARCHAR2(45) NOT NULL,
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES BOOK_USER (username)
);

CREATE SEQUENCE ROLE_SEQUENCE
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE;