INSERT INTO USER_ROLES VALUES (ROLE_SEQUENCE.nextVal,'admin', 'ROLE_ADMIN');
INSERT INTO USER_ROLES VALUES (ROLE_SEQUENCE.nextVal,'geo', 'ROLE_ADMIN');
INSERT INTO USER_ROLES VALUES (ROLE_SEQUENCE.nextVal,'iulia', 'ROLE_ADMIN');
INSERT INTO USER_ROLES VALUES (ROLE_SEQUENCE.nextVal,'vali', 'ROLE_ADMIN');