CREATE TABLE BOOK_CATEGORY (
  CATEGORY_ID NUMBER(5) PRIMARY KEY,
  TYPE VARCHAR2(255),
  BOOK_ID NUMBER(5) REFERENCES BOOK(BOOK_ID)
);

CREATE SEQUENCE CATEGORY_SEQUENCE
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE;